apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate

metadata:
  name: flask-demo-analysis

  labels:
    {{- include "flask-demo.labels" . | nindent 4 }}

spec:
  metrics:
    - name: error-rate

      interval: 15s

      count: 6

      failureLimit: 1

      successCondition: result[0] < {{ .Values.analysis.maxErrorRate }}

      provider:
        prometheus:

          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090

          query: |
            (
              sum(
                rate(
                  flask_http_request_total{
                    status=~"5.."
                  }[1m]
                )
              )
              /
              clamp_min(
                sum(
                  rate(
                    flask_http_request_total[1m]
                  )
                ),
                1
              )
            ) * 100