apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: {{ include "flask-demo.fullname" . }}
  labels:
    {{- include "flask-demo.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.rollout.replicas }}

  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}

  progressDeadlineSeconds: {{ .Values.rollout.progressDeadlineSeconds }}

  progressDeadlineAbort: {{ .Values.rollout.progressDeadlineAbort }}

  selector:
    matchLabels:
      {{- include "flask-demo.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "flask-demo.selectorLabels" . | nindent 8 }}

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.container.port }}"
        prometheus.io/path: "/metrics"

    spec:
      serviceAccountName: {{ include "flask-demo.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ include "flask-demo.name" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}

          env:
            - name: APP_NAME
              value: "{{ .Values.env.APP_NAME }}"

            - name: APP_VERSION
              value: "{{ .Values.env.APP_VERSION }}"

            - name: ENVIRONMENT
              value: "{{ .Values.env.ENVIRONMENT }}"

            - name: FAILURE_RATE
              value: "{{ .Values.env.FAILURE_RATE }}"

            - name: RESPONSE_DELAY
              value: "{{ .Values.env.RESPONSE_DELAY }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http

            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http

            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

  strategy:
    canary:

      stableService: {{ include "flask-demo.fullname" . }}-stable

      canaryService: {{ include "flask-demo.fullname" . }}-canary

      trafficRouting:
        nginx:
          stableIngress: {{ include "flask-demo.fullname" . }}

      steps:
        {{- toYaml .Values.rollout.strategy.canary.steps | nindent 8 }}